#!/bin/sh

LOGGER() {
  printf '[%s]\t%s\n' "$(date +'%Y-%m-%d %H:%M:%S')" "$*"
}

GET_OS() {
    unameOut="$(uname -s)"
    case "${unameOut}" in
      Linux*)     os=linux ;;
      Darwin*)    os=mac ;;
      CYGWIN*)    os=cygwin ;;
      MINGW*)     os=mingw ;;
      MSYS_NT*)   os=git ;;
      *)          os="UNKNOWN:${unameOut}" ;;
    esac
    printf '%s' "${os}"
}

CHECK_DOCKER() {
    LOGGER "[Docker test]  Checking the docker service..."

    if (! docker stats --no-stream > /dev/null 2>&1); then
        # On Mac OS this would be the terminal command to launch Docker
        if ! open /Applications/Docker.app; then
            LOGGER "[Docker test] Fail at open Docker.app"
            exit 1
        fi
        LOGGER "[Docker test]  Docker stopped! "
        sleep 1
        LOGGER "[Docker test]  ==> Starting"
        # Wait until Docker daemon is running and has completed initialisation
        while (! docker stats --no-stream > /dev/null 2>&1); do
            # Docker takes a few seconds to initialize
            sleep 1
        done
    fi
    LOGGER "[Docker test]  Docker started!"
}

## MAIN ##

# Abortar si no estamos en un MAC
if [ "$(GET_OS)" = "mac" ]; then
    # Chequear y levantar Docker
    CHECK_DOCKER
else
    LOGGER "[Docker test]  OS is not macOS... aborting!"
fi

exit 0